[
project
]
name = "autoarknights"
version = "0.1.0"
description = "A QQ bot for  Arklights game automation based on Nonebot2"
authors = [
    { name = "frinda", email = "114514@1919180.com" }
]
dependencies = [
    "nonebot2>=2.2.0",
    "nonebot-adapter-onebot>=2.4.0",
    "nb-cli>=1.0.0",
    "aiohttp>=3.8.0",      # 异步HTTP请求
    "pillow>=9.0.0",       # 图片处理
    "pydantic>=2.0.0",     # 数据验证
    "sqlalchemy>=2.0.0",   # 数据库ORM
    "asyncio>=3.4.3",      # 异步支持
    "nonebot-plugin-apscheduler>=^0.3.0"  #定时任务
]
requires-python = ">=3.8"

[
build-system
]
requires = ["hatchling"]
build-backend = "hatchling.build"

[
tool.nonebot
]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = []
plugin_dirs = ["autoarknights/plugins"]